version: '3'
services:
  transport-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: transport_db
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex
    ports:
      - "5432:5432"
  transport-app:
    build: .
    depends_on:
      - transport-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://transport-db:5432/transport_db
      SPRING_DATASOURCE_USERNAME: alex
      SPRING_DATASOURCE_PASSWORD: alex
